using BeyondImmersion.BannouService.Testing;
using BeyondImmersion.BannouService.Voice;

namespace BeyondImmersion.BannouService.HttpTester.Tests;

/// <summary>
/// Test handler for voice API endpoints using generated clients.
/// Tests the voice service APIs directly via NSwag-generated VoiceClient.
///
/// Note: Voice rooms are associated with game sessions and require valid session context.
/// These tests use synthetic SIP endpoints for testing purposes.
/// </summary>
public class VoiceTestHandler : IServiceTestHandler
{
    public ServiceTest[] GetServiceTests()
    {
        return new[]
        {
            // Core CRUD operations
            new ServiceTest(TestCreateVoiceRoom, "CreateVoiceRoom", "Voice", "Test voice room creation endpoint"),
            new ServiceTest(TestGetVoiceRoom, "GetVoiceRoom", "Voice", "Test voice room retrieval endpoint"),

            // Participant operations
            new ServiceTest(TestJoinVoiceRoom, "JoinVoiceRoom", "Voice", "Test joining a voice room"),
            new ServiceTest(TestLeaveVoiceRoom, "LeaveVoiceRoom", "Voice", "Test leaving a voice room"),
            new ServiceTest(TestPeerHeartbeat, "PeerHeartbeat", "Voice", "Test peer heartbeat mechanism"),

            // Cleanup operations
            new ServiceTest(TestDeleteVoiceRoom, "DeleteVoiceRoom", "Voice", "Test voice room deletion"),

            // Error handling tests
            new ServiceTest(TestGetNonExistentRoom, "GetNonExistentRoom", "Voice", "Test 404 for non-existent room"),

            // Complete lifecycle test
            new ServiceTest(TestCompleteVoiceLifecycle, "CompleteVoiceLifecycle", "Voice", "Test complete voice room lifecycle: create → join → heartbeat → leave → delete"),
        };
    }

    /// <summary>
    /// Creates a synthetic SDP offer for testing purposes.
    /// In production, this would be generated by WebRTC.
    /// </summary>
    private static string CreateTestSdpOffer()
    {
        return @"v=0
o=- 0 0 IN IP4 127.0.0.1
s=Test Session
c=IN IP4 127.0.0.1
t=0 0
m=audio 5004 RTP/AVP 111
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=sendrecv";
    }

    private static async Task<TestResult> TestCreateVoiceRoom(ITestClient client, string[] args)
    {
        try
        {
            var voiceClient = new VoiceClient();

            var createRequest = new CreateVoiceRoomRequest
            {
                SessionId = Guid.NewGuid(), // Synthetic game session ID for testing
                PreferredTier = VoiceTier.P2p,
                MaxParticipants = 6,
                Codec = VoiceCodec.Opus
            };

            var response = await voiceClient.CreateVoiceRoomAsync(createRequest);

            if (response.RoomId == Guid.Empty)
                return TestResult.Failed("Voice room creation returned empty room ID");

            if (response.Tier != VoiceTier.P2p)
                return TestResult.Failed($"Tier mismatch: expected 'p2p', got '{response.Tier}'");

            return TestResult.Successful($"Voice room created successfully: ID={response.RoomId}, Tier={response.Tier}");
        }
        catch (ApiException ex)
        {
            return TestResult.Failed($"Voice room creation failed: {ex.StatusCode} - {ex.Message}");
        }
        catch (Exception ex)
        {
            return TestResult.Failed($"Test exception: {ex.Message}", ex);
        }
    }

    private static async Task<TestResult> TestGetVoiceRoom(ITestClient client, string[] args)
    {
        try
        {
            var voiceClient = new VoiceClient();

            // First create a test room
            var createRequest = new CreateVoiceRoomRequest
            {
                SessionId = Guid.NewGuid(),
                PreferredTier = VoiceTier.P2p,
                MaxParticipants = 6,
                Codec = VoiceCodec.Opus
            };

            var createResponse = await voiceClient.CreateVoiceRoomAsync(createRequest);
            if (createResponse.RoomId == Guid.Empty)
                return TestResult.Failed("Failed to create test room for retrieval test");

            // Now test retrieving the room
            var getRequest = new GetVoiceRoomRequest { RoomId = createResponse.RoomId };
            var response = await voiceClient.GetVoiceRoomAsync(getRequest);

            if (response.RoomId != createResponse.RoomId)
                return TestResult.Failed($"Room ID mismatch: expected '{createResponse.RoomId}', got '{response.RoomId}'");

            return TestResult.Successful($"Voice room retrieved successfully: ID={response.RoomId}, Tier={response.Tier}");
        }
        catch (ApiException ex)
        {
            return TestResult.Failed($"Voice room retrieval failed: {ex.StatusCode} - {ex.Message}");
        }
        catch (Exception ex)
        {
            return TestResult.Failed($"Test exception: {ex.Message}", ex);
        }
    }

    private static async Task<TestResult> TestJoinVoiceRoom(ITestClient client, string[] args)
    {
        try
        {
            var voiceClient = new VoiceClient();

            // First create a test room
            var createRequest = new CreateVoiceRoomRequest
            {
                SessionId = Guid.NewGuid(),
                PreferredTier = VoiceTier.P2p,
                MaxParticipants = 6,
                Codec = VoiceCodec.Opus
            };

            var createResponse = await voiceClient.CreateVoiceRoomAsync(createRequest);
            if (createResponse.RoomId == Guid.Empty)
                return TestResult.Failed("Failed to create test room for join test");

            // Now test joining the room
            var sessionId = Guid.NewGuid().ToString();
            var joinRequest = new JoinVoiceRoomRequest
            {
                RoomId = createResponse.RoomId,
                SessionId = sessionId,
                DisplayName = "TestUser",
                SipEndpoint = new SipEndpoint
                {
                    SdpOffer = CreateTestSdpOffer(),
                    IceCandidates = new List<string>(),
                    Port = 5004
                }
            };

            var response = await voiceClient.JoinVoiceRoomAsync(joinRequest);

            if (response.RoomId != createResponse.RoomId)
                return TestResult.Failed($"Room ID mismatch in join response");

            return TestResult.Successful($"Successfully joined voice room: RoomID={createResponse.RoomId}, Tier={response.Tier}");
        }
        catch (ApiException ex)
        {
            return TestResult.Failed($"Join voice room failed: {ex.StatusCode} - {ex.Message}");
        }
        catch (Exception ex)
        {
            return TestResult.Failed($"Test exception: {ex.Message}", ex);
        }
    }

    private static async Task<TestResult> TestLeaveVoiceRoom(ITestClient client, string[] args)
    {
        try
        {
            var voiceClient = new VoiceClient();

            // Create and join a room first
            var createRequest = new CreateVoiceRoomRequest
            {
                SessionId = Guid.NewGuid(),
                PreferredTier = VoiceTier.P2p,
                MaxParticipants = 6,
                Codec = VoiceCodec.Opus
            };

            var createResponse = await voiceClient.CreateVoiceRoomAsync(createRequest);
            var sessionId = Guid.NewGuid().ToString();

            // Join the room
            var joinRequest = new JoinVoiceRoomRequest
            {
                RoomId = createResponse.RoomId,
                SessionId = sessionId,
                DisplayName = "TestUser",
                SipEndpoint = new SipEndpoint
                {
                    SdpOffer = CreateTestSdpOffer(),
                    IceCandidates = new List<string>()
                }
            };
            await voiceClient.JoinVoiceRoomAsync(joinRequest);

            // Now test leaving the room
            var leaveRequest = new LeaveVoiceRoomRequest
            {
                RoomId = createResponse.RoomId,
                SessionId = sessionId
            };
            await voiceClient.LeaveVoiceRoomAsync(leaveRequest);

            return TestResult.Successful($"Successfully left voice room: RoomID={createResponse.RoomId}");
        }
        catch (ApiException ex)
        {
            return TestResult.Failed($"Leave voice room failed: {ex.StatusCode} - {ex.Message}");
        }
        catch (Exception ex)
        {
            return TestResult.Failed($"Test exception: {ex.Message}", ex);
        }
    }

    private static async Task<TestResult> TestPeerHeartbeat(ITestClient client, string[] args)
    {
        try
        {
            var voiceClient = new VoiceClient();

            // Create and join a room first
            var createRequest = new CreateVoiceRoomRequest
            {
                SessionId = Guid.NewGuid(),
                PreferredTier = VoiceTier.P2p,
                MaxParticipants = 6,
                Codec = VoiceCodec.Opus
            };

            var createResponse = await voiceClient.CreateVoiceRoomAsync(createRequest);
            var sessionId = Guid.NewGuid().ToString();

            // Join the room
            var joinRequest = new JoinVoiceRoomRequest
            {
                RoomId = createResponse.RoomId,
                SessionId = sessionId,
                DisplayName = "TestUser",
                SipEndpoint = new SipEndpoint
                {
                    SdpOffer = CreateTestSdpOffer(),
                    IceCandidates = new List<string>()
                }
            };
            await voiceClient.JoinVoiceRoomAsync(joinRequest);

            // Now test sending a heartbeat
            var heartbeatRequest = new PeerHeartbeatRequest
            {
                RoomId = createResponse.RoomId,
                SessionId = sessionId
            };
            await voiceClient.PeerHeartbeatAsync(heartbeatRequest);

            return TestResult.Successful($"Peer heartbeat sent successfully: RoomID={createResponse.RoomId}");
        }
        catch (ApiException ex)
        {
            return TestResult.Failed($"Peer heartbeat failed: {ex.StatusCode} - {ex.Message}");
        }
        catch (Exception ex)
        {
            return TestResult.Failed($"Test exception: {ex.Message}", ex);
        }
    }

    private static async Task<TestResult> TestDeleteVoiceRoom(ITestClient client, string[] args)
    {
        try
        {
            var voiceClient = new VoiceClient();

            // Create a room first
            var createRequest = new CreateVoiceRoomRequest
            {
                SessionId = Guid.NewGuid(),
                PreferredTier = VoiceTier.P2p,
                MaxParticipants = 6,
                Codec = VoiceCodec.Opus
            };

            var createResponse = await voiceClient.CreateVoiceRoomAsync(createRequest);
            if (createResponse.RoomId == Guid.Empty)
                return TestResult.Failed("Failed to create test room for delete test");

            // Now test deleting the room
            var deleteRequest = new DeleteVoiceRoomRequest
            {
                RoomId = createResponse.RoomId,
                Reason = "test_cleanup"
            };
            await voiceClient.DeleteVoiceRoomAsync(deleteRequest);

            // Verify deletion by attempting to get the room
            try
            {
                var getRequest = new GetVoiceRoomRequest { RoomId = createResponse.RoomId };
                await voiceClient.GetVoiceRoomAsync(getRequest);
                return TestResult.Failed("Room still exists after deletion");
            }
            catch (ApiException ex) when (ex.StatusCode == 404)
            {
                // Expected - room was deleted
            }

            return TestResult.Successful($"Voice room deleted successfully: RoomID={createResponse.RoomId}");
        }
        catch (ApiException ex)
        {
            return TestResult.Failed($"Delete voice room failed: {ex.StatusCode} - {ex.Message}");
        }
        catch (Exception ex)
        {
            return TestResult.Failed($"Test exception: {ex.Message}", ex);
        }
    }

    private static async Task<TestResult> TestGetNonExistentRoom(ITestClient client, string[] args)
    {
        try
        {
            var voiceClient = new VoiceClient();

            var getRequest = new GetVoiceRoomRequest
            {
                RoomId = Guid.NewGuid() // Non-existent room ID
            };

            try
            {
                await voiceClient.GetVoiceRoomAsync(getRequest);
                return TestResult.Failed("Expected 404 for non-existent room, but request succeeded");
            }
            catch (ApiException ex) when (ex.StatusCode == 404)
            {
                return TestResult.Successful("Correctly returned 404 for non-existent room");
            }
        }
        catch (ApiException ex)
        {
            return TestResult.Failed($"Unexpected error: {ex.StatusCode} - {ex.Message}");
        }
        catch (Exception ex)
        {
            return TestResult.Failed($"Test exception: {ex.Message}", ex);
        }
    }

    private static async Task<TestResult> TestCompleteVoiceLifecycle(ITestClient client, string[] args)
    {
        try
        {
            var voiceClient = new VoiceClient();

            // Step 1: Create room
            var createRequest = new CreateVoiceRoomRequest
            {
                SessionId = Guid.NewGuid(),
                PreferredTier = VoiceTier.P2p,
                MaxParticipants = 6,
                Codec = VoiceCodec.Opus
            };

            var createResponse = await voiceClient.CreateVoiceRoomAsync(createRequest);
            Console.WriteLine($"  Step 1: Created voice room {createResponse.RoomId}");

            // Step 2: Join room
            var sessionId = Guid.NewGuid().ToString();
            var joinRequest = new JoinVoiceRoomRequest
            {
                RoomId = createResponse.RoomId,
                SessionId = sessionId,
                DisplayName = "LifecycleTestUser",
                SipEndpoint = new SipEndpoint
                {
                    SdpOffer = CreateTestSdpOffer(),
                    IceCandidates = new List<string>()
                }
            };
            await voiceClient.JoinVoiceRoomAsync(joinRequest);
            Console.WriteLine($"  Step 2: User joined room");

            // Step 3: Send heartbeat
            var heartbeatRequest = new PeerHeartbeatRequest
            {
                RoomId = createResponse.RoomId,
                SessionId = sessionId
            };
            await voiceClient.PeerHeartbeatAsync(heartbeatRequest);
            Console.WriteLine($"  Step 3: Heartbeat sent");

            // Step 4: Leave room
            var leaveRequest = new LeaveVoiceRoomRequest
            {
                RoomId = createResponse.RoomId,
                SessionId = sessionId
            };
            await voiceClient.LeaveVoiceRoomAsync(leaveRequest);
            Console.WriteLine($"  Step 4: User left room");

            // Step 5: Delete room
            var deleteRequest = new DeleteVoiceRoomRequest
            {
                RoomId = createResponse.RoomId,
                Reason = "lifecycle_test_complete"
            };
            await voiceClient.DeleteVoiceRoomAsync(deleteRequest);
            Console.WriteLine($"  Step 5: Room deleted");

            // Step 6: Verify deletion
            try
            {
                var getRequest = new GetVoiceRoomRequest { RoomId = createResponse.RoomId };
                await voiceClient.GetVoiceRoomAsync(getRequest);
                return TestResult.Failed("Room still exists after deletion in lifecycle test");
            }
            catch (ApiException ex) when (ex.StatusCode == 404)
            {
                Console.WriteLine($"  Step 6: Deletion verified");
            }

            return TestResult.Successful($"Complete voice room lifecycle test passed for room {createResponse.RoomId}");
        }
        catch (ApiException ex)
        {
            return TestResult.Failed($"Lifecycle test failed: {ex.StatusCode} - {ex.Message}");
        }
        catch (Exception ex)
        {
            return TestResult.Failed($"Test exception: {ex.Message}", ex);
        }
    }
}
