using BeyondImmersion.BannouService.Attributes;
using System.Reflection;

namespace BeyondImmersion.BannouService.TestUtilities;

/// <summary>
/// Validates that services with [ResourceCleanupRequired] attributes have
/// corresponding cleanup methods implemented.
/// </summary>
/// <remarks>
/// <para>
/// The [ResourceCleanupRequired] attribute is generated by generate-references.py
/// from x-references declarations that include cleanup endpoints. The attribute
/// carries the expected method name derived from the endpoint path
/// (e.g., <c>/status/cleanup-by-owner</c> → <c>CleanupByOwnerAsync</c>).
/// This validator ensures the service actually implements the method that
/// lib-resource will call at runtime.
/// </para>
/// </remarks>
public static class ResourceCleanupValidator
{
    /// <summary>
    /// Validates that a service type has all cleanup methods declared by
    /// [ResourceCleanupRequired] attributes.
    /// </summary>
    /// <param name="serviceType">The [BannouService]-attributed service type.</param>
    /// <returns>List of missing cleanup method names, or empty if all present.</returns>
    public static string[] GetMissingCleanupMethods(Type serviceType)
    {
        ArgumentNullException.ThrowIfNull(serviceType);

        var requiredMethods = serviceType
            .GetCustomAttributes<ResourceCleanupRequiredAttribute>()
            .Select(a => a.MethodName)
            .Distinct()
            .ToArray();

        if (requiredMethods.Length == 0)
            return [];

        var missing = new List<string>();

        foreach (var expectedMethodName in requiredMethods)
        {
            var method = serviceType.GetMethod(
                expectedMethodName,
                BindingFlags.Public | BindingFlags.Instance);

            if (method == null)
            {
                missing.Add(expectedMethodName);
            }
        }

        return missing.ToArray();
    }
}
