#!/bin/bash
# Generate TypeScript types from the consolidated client OpenAPI schema.
# This script uses the consolidated schema generated by generate-client-schema.py.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENT_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(cd "$CLIENT_DIR/../../.." && pwd)"
SCHEMA_FILE="$REPO_ROOT/schemas/Generated/bannou-client-api.yaml"
OUTPUT_DIR="$CLIENT_DIR/src/Generated/types"

# Verify consolidated schema exists
if [ ! -f "$SCHEMA_FILE" ]; then
    echo "ERROR: Consolidated client schema not found: $SCHEMA_FILE"
    echo "       Run 'make generate-client-schema' first."
    exit 1
fi

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Clean up old generated files
rm -f "$OUTPUT_DIR"/*.ts "$OUTPUT_DIR"/*.d.ts

echo "Generating TypeScript types from consolidated client schema..."
echo "  Reading from: schemas/Generated/bannou-client-api.yaml"
echo "  Writing to: $OUTPUT_DIR/"
echo

# Generate types from consolidated schema
echo "  Processing bannou-client-api.yaml..."
npx openapi-typescript "$SCHEMA_FILE" --output "$OUTPUT_DIR/bannou-client-api.ts" 2>/dev/null || {
    echo "    ERROR: Failed to generate types from consolidated schema"
    exit 1
}

# Generate index file that re-exports all types
cat > "$OUTPUT_DIR/index.ts" << 'EOF'
// <auto-generated>
// Generated by generate-types.sh
// Do not edit this file manually.
//
// Re-exports types from the consolidated client schema.
// </auto-generated>

export * from './bannou-client-api.js';
EOF

echo
echo "Generated types from consolidated client schema"
