#!/bin/bash
# Generate TypeScript types from OpenAPI schemas using openapi-typescript.
# This script processes each *-api.yaml schema and generates a corresponding .d.ts file.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENT_DIR="$(dirname "$SCRIPT_DIR")"
REPO_ROOT="$(cd "$CLIENT_DIR/../../.." && pwd)"
SCHEMA_DIR="$REPO_ROOT/schemas"
OUTPUT_DIR="$CLIENT_DIR/src/Generated/types"

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Clean up old generated files
rm -f "$OUTPUT_DIR"/*.ts "$OUTPUT_DIR"/*.d.ts

echo "Generating TypeScript types from OpenAPI schemas..."
echo "  Reading from: $SCHEMA_DIR/*-api.yaml"
echo "  Writing to: $OUTPUT_DIR/"
echo

# Count for reporting
count=0

# Process each API schema
for schema in "$SCHEMA_DIR"/*-api.yaml; do
    if [ -f "$schema" ]; then
        # Extract service name from filename (e.g., auth-api.yaml -> auth-api)
        basename=$(basename "$schema" .yaml)
        output_file="$OUTPUT_DIR/${basename}.ts"

        echo "  Processing $basename.yaml..."
        npx openapi-typescript "$schema" --output "$output_file" 2>/dev/null || {
            echo "    Warning: Failed to generate types for $basename"
            continue
        }

        ((count++)) || true
    fi
done

# Generate index file that re-exports all types
echo "// <auto-generated>" > "$OUTPUT_DIR/index.ts"
echo "// Generated by generate-types.sh" >> "$OUTPUT_DIR/index.ts"
echo "// Do not edit this file manually." >> "$OUTPUT_DIR/index.ts"
echo "//" >> "$OUTPUT_DIR/index.ts"
echo "// Re-exports types from all generated schema files." >> "$OUTPUT_DIR/index.ts"
echo "// </auto-generated>" >> "$OUTPUT_DIR/index.ts"
echo "" >> "$OUTPUT_DIR/index.ts"

for schema in "$SCHEMA_DIR"/*-api.yaml; do
    if [ -f "$schema" ]; then
        basename=$(basename "$schema" .yaml)
        if [ -f "$OUTPUT_DIR/${basename}.ts" ]; then
            echo "export * from './${basename}.js';" >> "$OUTPUT_DIR/index.ts"
        fi
    fi
done

echo "" >> "$OUTPUT_DIR/index.ts"

echo
echo "Generated types for $count schemas"
