#!/bin/bash

# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔
# This script is part of Bannou's code generation pipeline.
# DO NOT MODIFY without EXPLICIT user instructions to change code generation.
#
# Changes to generation scripts silently break builds across ALL 48 services.
# An agent once changed namespace strings across 4 scripts in a single commit,
# breaking every service. If you believe a change is needed:
#   1. STOP and explain what you think is wrong
#   2. Show the EXACT diff you propose
#   3. Wait for EXPLICIT approval before touching ANY generation script
#
# This applies to: namespace strings, output paths, exclusion logic,
# NSwag parameters, post-processing steps, and file naming conventions.
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔

# Generate archive models from plugin schemas into storyline-theory SDK
# This generates typed archive classes for storyline SDK consumption
# Types marked with x-archive-type: true are extracted and generated with
# namespace BeyondImmersion.Bannou.StorylineTheory.Archives
#
# Workflow:
# 1. extract-archive-schemas.py creates consolidated schema with archive types
# 2. NSwag generates C# from consolidated schema
# 3. Post-processing adds headers and suppressions

set -e

# Change to scripts directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Source common utilities
source "./common.sh"

log_info "Generating archive models for storyline-theory SDK"

# Find NSwag executable and ensure DOTNET_ROOT is set
require_nswag
ensure_dotnet_root

OUTPUT_DIR="../sdks/storyline-theory/Generated/Archives"
NAMESPACE="BeyondImmersion.Bannou.StorylineTheory.Archives"
CONSOLIDATED_SCHEMA="../schemas/Generated/storyline-archives.yaml"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Step 1: Extract archive schemas into consolidated file
echo -e "${YELLOW}Step 1: Extracting archive schemas...${NC}"
python3 "$SCRIPT_DIR/extract-archive-schemas.py"

if [ ! -f "$CONSOLIDATED_SCHEMA" ]; then
    echo -e "${RED}No archive schemas found - nothing to generate${NC}"
    exit 0
fi

# Step 2: Generate C# from consolidated schema
echo ""
echo -e "${YELLOW}Step 2: Generating C# models...${NC}"
echo -e "  Output: $OUTPUT_DIR"
echo -e "  Namespace: $NAMESPACE"

OUTPUT_FILE="$OUTPUT_DIR/ArchiveModels.cs"

"$NSWAG_EXE" openapi2csclient \
    "/input:$CONSOLIDATED_SCHEMA" \
    "/output:$OUTPUT_FILE" \
    "/namespace:$NAMESPACE" \
    "/generateClientClasses:false" \
    "/generateClientInterfaces:false" \
    "/generateDtoTypes:true" \
    "/excludedTypeNames:ApiException,ApiException\<TResult\>" \
    "/jsonLibrary:SystemTextJson" \
    "/generateNullableReferenceTypes:true" \
    "/newLineBehavior:LF" \
    "/templateDirectory:../templates/nswag"

if [ $? -ne 0 ] || [ ! -f "$OUTPUT_FILE" ]; then
    echo -e "${RED}Failed to generate archive models${NC}"
    exit 1
fi

# Step 3: Post-processing
echo ""
echo -e "${YELLOW}Step 3: Post-processing...${NC}"

# Add warning header
TEMP_FILE=$(mktemp)
cat > "$TEMP_FILE" << 'HEADER'
//----------------------
// <auto-generated>
//     Generated from plugin schemas for storyline-theory SDK.
//
//     WARNING: DO NOT EDIT THIS FILE
//     Regenerate with: scripts/generate-storyline-archives.sh
//
//     These archive types are used by the storyline SDK to interpret
//     compressed character/realm data without direct plugin dependencies.
//
//     Source: Types marked with x-archive-type: true in plugin *-api.yaml schemas
// </auto-generated>
//----------------------

HEADER
cat "$OUTPUT_FILE" >> "$TEMP_FILE"
mv "$TEMP_FILE" "$OUTPUT_FILE"

# Post-process: Add enum CS1591 suppressions
postprocess_enum_suppressions "$OUTPUT_FILE"

# Post-process: Add AdditionalProperties XML docs
postprocess_additional_properties_docs "$OUTPUT_FILE"

# Post-process: Convert enum names to PascalCase
postprocess_enum_pascalcase "$OUTPUT_FILE"

LINES=$(wc -l < "$OUTPUT_FILE")
echo -e "${GREEN}Generated: $OUTPUT_FILE ($LINES lines)${NC}"

# Print summary
echo ""
echo -e "${GREEN}Archive models generated successfully!${NC}"
echo -e "${BLUE}Available in namespace: $NAMESPACE${NC}"

# List generated types
echo ""
echo -e "${BLUE}Archive types:${NC}"
grep -o "public partial class [A-Za-z]*Archive" "$OUTPUT_FILE" | sed 's/public partial class /  - /' || true
