#!/usr/bin/env python3
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔
# This script is part of Bannou's code generation pipeline.
# DO NOT MODIFY without EXPLICIT user instructions to change code generation.
#
# Changes to generation scripts silently break builds across ALL 76+ services.
# An agent once changed namespace strings across 4 scripts in a single commit,
# breaking every service. If you believe a change is needed:
#   1. STOP and explain what you think is wrong
#   2. Show the EXACT diff you propose
#   3. Wait for EXPLICIT approval before touching ANY generation script
#
# This applies to: namespace strings, output paths, exclusion logic,
# NSwag parameters, post-processing steps, and file naming conventions.
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔

"""
Generate Localization Category Code and Documentation from Schema.

This script reads schemas/localization-categories.yaml and generates:
1. bannou-service/Generated/LocalizationCategoryDefinitions.cs - Typed constants and metadata
2. docs/generated/GENERATED-LOCALIZATION-CATEGORIES.md - Documentation

Usage:
    python3 scripts/generate-localization-categories.py
"""

import re
import sys
from pathlib import Path

# Use ruamel.yaml to parse YAML files
try:
    from ruamel.yaml import YAML
    yaml = YAML()
    yaml.preserve_quotes = True
except ImportError:
    print("ERROR: ruamel.yaml is required. Install with: pip install ruamel.yaml")
    sys.exit(1)


def to_pascal_case(name: str) -> str:
    """Convert kebab-case or snake_case to PascalCase."""
    # Split on hyphens and underscores
    parts = re.split(r'[-_]', name)
    # Capitalize each part
    return ''.join(p.capitalize() for p in parts)


def generate_csharp(categories: dict) -> str:
    """Generate C# code for LocalizationCategoryDefinitions.cs."""
    lines = [
        "// <auto-generated>",
        "// This file is auto-generated from schemas/localization-categories.yaml",
        "// Do not edit manually - regenerate with: python3 scripts/generate-localization-categories.py",
        "//",
        "// Localization category codes are used as arguments to ILocalizationKeyValidator.",
        "// All callers MUST use these constants — hardcoded category strings are forbidden.",
        "// Structural tests enforce this on both sides (constants referenced, validator uses constants).",
        "// See: docs/plugins/LOCALIZATION.md",
        "// </auto-generated>",
        "",
        "#nullable enable",
        "",
        "using BeyondImmersion.BannouService.Localization;",
        "",
        "namespace BeyondImmersion.BannouService.Services;",
        "",
        "/// <summary>",
        "/// Localization category code constants and metadata definitions.",
        "/// Generated from schemas/localization-categories.yaml.",
        "/// </summary>",
        "public static class LocalizationCategoryDefinitions",
        "{",
        "    #region Category Code Constants",
        "",
    ]

    # Generate constants sorted by name
    for cat_name in sorted(categories.keys()):
        cat_config = categories[cat_name]
        const_name = to_pascal_case(cat_name)
        description = cat_config.get('description', '')
        validation_mode = cat_config.get('validationMode', 'None')
        lines.append(f"    /// <summary>{description} (validation: {validation_mode})</summary>")
        lines.append(f'    public const string {const_name} = "{cat_name}";')
        lines.append("")

    lines.append("    #endregion")
    lines.append("")
    lines.append("    #region Metadata")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// Category metadata for documentation, validation, and tooling.")
    lines.append("    /// </summary>")
    lines.append("    public static readonly IReadOnlyDictionary<string, LocalizationCategoryMetadata> Metadata =")
    lines.append("        new Dictionary<string, LocalizationCategoryMetadata>")
    lines.append("        {")

    for cat_name in sorted(categories.keys()):
        cat_config = categories[cat_name]
        const_name = to_pascal_case(cat_name)
        description = cat_config.get('description', '').replace('"', '\\"')
        validation_mode = cat_config.get('validationMode', 'None')
        consumers = cat_config.get('consumers', [])
        if consumers:
            consumers_str = ', '.join(f'"{c}"' for c in consumers)
            consumers_array = f'new[] {{ {consumers_str} }}'
        else:
            consumers_array = 'Array.Empty<string>()'
        lines.append(
            f'            [{const_name}] = new LocalizationCategoryMetadata('
            f'"{description}", '
            f'ValidationMode.{validation_mode}, '
            f'{consumers_array}),'
        )

    lines.append("        };")
    lines.append("")
    lines.append("    #endregion")
    lines.append("}")
    lines.append("")
    lines.append("/// <summary>")
    lines.append("/// Metadata about a localization category for documentation and tooling.")
    lines.append("/// </summary>")
    lines.append("/// <param name=\"Description\">Human-readable description of the category's purpose.</param>")
    lines.append("/// <param name=\"ValidationMode\">Validation behavior (None, WarnOnMissing, RejectOnMissing).</param>")
    lines.append("/// <param name=\"Consumers\">Plugin assemblies declared as consumers of this category.</param>")
    lines.append("public readonly record struct LocalizationCategoryMetadata(string Description, ValidationMode ValidationMode, string[] Consumers);")
    lines.append("")

    return '\n'.join(lines)


def generate_markdown(categories: dict) -> str:
    """Generate markdown documentation for GENERATED-LOCALIZATION-CATEGORIES.md."""
    lines = [
        "# Generated Localization Category Reference",
        "",
        "> **Source**: `schemas/localization-categories.yaml`",
        "> **Do not edit manually** - regenerate with `make generate-docs`",
        "",
        "This document lists all localization categories used by Bannou services.",
        "Categories organize translation entries by domain. Schema-defined categories",
        "are seeded on startup and cannot be deleted via API.",
        "",
        "## Localization Categories",
        "",
        "| Category Code | Validation Mode | Consumers | Description |",
        "|---------------|-----------------|-----------|-------------|",
    ]

    # Sort categories by name
    for cat_name in sorted(categories.keys()):
        cat_config = categories[cat_name]
        description = cat_config.get('description', '')
        validation_mode = cat_config.get('validationMode', 'None')
        consumers = cat_config.get('consumers', [])
        consumers_str = ', '.join(f'`{c}`' for c in consumers) if consumers else '*(none)*'
        lines.append(f"| `{cat_name}` | {validation_mode} | {consumers_str} | {description} |")

    # Count by validation mode
    none_count = sum(1 for c in categories.values() if c.get('validationMode', 'None') == 'None')
    warn_count = sum(1 for c in categories.values() if c.get('validationMode') == 'WarnOnMissing')
    reject_count = sum(1 for c in categories.values() if c.get('validationMode') == 'RejectOnMissing')

    lines.extend([
        "",
        f"**Total**: {len(categories)} categories ({reject_count} RejectOnMissing, {warn_count} WarnOnMissing, {none_count} None)",
        "",
        "## Validation Modes",
        "",
        "| Mode | Behavior |",
        "|------|----------|",
        "| `None` | Key validation always returns true (no checking) |",
        "| `WarnOnMissing` | Returns true but logs a warning when a key doesn't exist |",
        "| `RejectOnMissing` | Returns false when a key doesn't exist (caller gets BadRequest) |",
        "",
        "Validation mode is configured per category and controls the behavior of",
        "`ILocalizationKeyValidator.ValidateLocalizationKeyAsync()` when called by",
        "consumer plugins at entity creation time.",
        "",
        "## How Categories Work",
        "",
        "1. **Schema**: Categories are defined in `schemas/localization-categories.yaml`",
        "2. **Constants**: Generated to `LocalizationCategoryDefinitions` in `bannou-service/Generated/`",
        "3. **Seeding**: Schema-defined categories are seeded on startup (idempotent, cannot be deleted via API)",
        "4. **Validation**: Consumer plugins call `ILocalizationKeyValidator` with generated constants",
        "5. **Runtime**: The API also supports runtime category CRUD for L5 extensions",
        "",
        "## Generated Code",
        "",
        "Localization category definitions are generated to `bannou-service/Generated/LocalizationCategoryDefinitions.cs`,",
        "providing:",
        "",
        "- **Code constants**: `LocalizationCategoryDefinitions.Items`, `LocalizationCategoryDefinitions.Quests`, etc.",
        "- **Metadata**: `LocalizationCategoryDefinitions.Metadata` with description, validation mode, and consumers",
        "",
        "## Structural Enforcement",
        "",
        "Two structural tests validate the localization category registry:",
        "",
        "| Test | What It Validates |",
        "|------|-------------------|",
        "| `LocalizationCategories_AreAllReferenced` | Every constant has at least one declared consumer in the schema |",
        "| `LocalizationValidator_UsesGeneratedConstants` | Every `ValidateLocalizationKeyAsync` call uses a `LocalizationCategoryDefinitions` constant |",
        "",
        "---",
        "",
        "*This file is auto-generated. See [TENETS.md](../reference/TENETS.md) for architectural context.*",
        "",
    ])

    return '\n'.join(lines)


def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent

    # Read schema
    schema_file = repo_root / 'schemas' / 'localization-categories.yaml'
    if not schema_file.exists():
        print(f"ERROR: Schema file not found: {schema_file}")
        sys.exit(1)

    with open(schema_file) as f:
        content = yaml.load(f)

    if content is None:
        print("ERROR: Failed to parse schema file")
        sys.exit(1)

    categories = content.get('x-localization-categories', {})
    if not categories:
        print("Warning: No localization categories defined in schema")

    # Generate C# code
    csharp_code = generate_csharp(categories)
    csharp_output = repo_root / 'bannou-service' / 'Generated' / 'LocalizationCategoryDefinitions.cs'
    csharp_output.parent.mkdir(parents=True, exist_ok=True)
    with open(csharp_output, 'w') as f:
        f.write(csharp_code)
    print(f"Generated {csharp_output}")

    # Generate documentation
    markdown = generate_markdown(categories)
    md_output = repo_root / 'docs' / 'generated' / 'GENERATED-LOCALIZATION-CATEGORIES.md'
    with open(md_output, 'w') as f:
        f.write(markdown)
    print(f"Generated {md_output}")

    print(f"Processed {len(categories)} localization categories")


if __name__ == '__main__':
    main()
