#!/bin/bash

# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔
# This script is part of Bannou's code generation pipeline.
# DO NOT MODIFY without EXPLICIT user instructions to change code generation.
#
# Changes to generation scripts silently break builds across ALL 48 services.
# An agent once changed namespace strings across 4 scripts in a single commit,
# breaking every service. If you believe a change is needed:
#   1. STOP and explain what you think is wrong
#   2. Show the EXACT diff you propose
#   3. Wait for EXPLICIT approval before touching ANY generation script
#
# This applies to: namespace strings, output paths, exclusion logic,
# NSwag parameters, post-processing steps, and file naming conventions.
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔

# Event Subscription Registry Generator
# Scans all *-events.yaml files and generates EventSubscriptionRegistration.cs
# This enables NativeEventConsumerBackend to deserialize events by topic name

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source common utilities
source "$SCRIPT_DIR/common.sh"
SCHEMAS_DIR="${SCRIPT_DIR}/../schemas"
OUTPUT_FILE="${SCRIPT_DIR}/../bannou-service/Generated/EventSubscriptionRegistration.cs"

echo -e "${BLUE}📡 Generating EventSubscriptionRegistration from all *-events.yaml files...${NC}"

# Ensure output directory exists
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Python script to extract all x-event-subscriptions from all event schema files
PYTHON_SCRIPT=$(cat << 'PYEOF'
import sys
import os
import json
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required but not found", file=sys.stderr)
    sys.exit(1)

schemas_dir = sys.argv[1]
all_subscriptions = []

# Find all *-events.yaml files (excluding client events)
for yaml_file in sorted(Path(schemas_dir).glob("*-events.yaml")):
    # Skip client event files - they're for WebSocket push, not pub/sub subscriptions
    if "-client-events.yaml" in str(yaml_file):
        continue

    try:
        with open(yaml_file, 'r') as f:
            schema = yaml.safe_load(f)

        info = schema.get('info', {})
        subscriptions = info.get('x-event-subscriptions', [])

        for sub in subscriptions:
            topic = sub.get('topic', '')
            event_type = sub.get('event', '')
            if topic and event_type:
                all_subscriptions.append({
                    'topic': topic,
                    'event': event_type,
                    'source': yaml_file.name
                })
    except Exception as e:
        print(f"Warning: Could not parse {yaml_file}: {e}", file=sys.stderr)

# Output as JSON
print(json.dumps(all_subscriptions))
PYEOF
)

# Extract subscriptions using Python
SUBSCRIPTIONS_JSON=""
if command -v python3 &> /dev/null; then
    SUBSCRIPTIONS_JSON=$(echo "$PYTHON_SCRIPT" | python3 - "$SCHEMAS_DIR" 2>/dev/null) || true
fi

if [ -z "$SUBSCRIPTIONS_JSON" ] || [ "$SUBSCRIPTIONS_JSON" == "[]" ]; then
    echo -e "${YELLOW}  No event subscriptions found in schema files${NC}"
    # Still generate an empty registration file
    SUBSCRIPTIONS_JSON="[]"
fi

# Count subscriptions
SUBSCRIPTION_COUNT=$(echo "$SUBSCRIPTIONS_JSON" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")
echo -e "  📊 Found $SUBSCRIPTION_COUNT event subscription(s) across all services"

# Generate the C# registration file
cat > "$OUTPUT_FILE" << 'CSHARP_HEADER'
// <auto-generated>
// This file was generated by generate-event-subscription-registry.sh
// Do not edit this file directly - changes will be overwritten.
// To add event subscriptions, edit x-event-subscriptions in the appropriate *-events.yaml schema.
// </auto-generated>

#nullable enable

using BeyondImmersion.BannouService.Events;

namespace BeyondImmersion.BannouService;

/// <summary>
/// Auto-generated event subscription registration.
/// Maps topic names to event types for the NativeEventConsumerBackend.
/// </summary>
public static class EventSubscriptionRegistration
{
    /// <summary>
    /// Registers all event types with their corresponding topic names.
    /// Call this during application startup to enable native messaging.
    /// </summary>
    public static void RegisterAll()
    {
CSHARP_HEADER

# Generate registration calls for each subscription
echo "$SUBSCRIPTIONS_JSON" | python3 -c "
import sys
import json

data = json.load(sys.stdin)
current_source = None

for sub in data:
    topic = sub.get('topic', '')
    event_type = sub.get('event', '')
    source = sub.get('source', '')

    if not topic or not event_type:
        continue

    # Add source file comment when switching files
    if source != current_source:
        if current_source is not None:
            print()
        print(f'        // From {source}')
        current_source = source

    print(f'        EventSubscriptionRegistry.Register<{event_type}>(\"{topic}\");')
" >> "$OUTPUT_FILE"

# Close the method and class
cat >> "$OUTPUT_FILE" << 'CSHARP_FOOTER'
    }
}
CSHARP_FOOTER

echo -e "${GREEN}✅ Generated: $OUTPUT_FILE${NC}"
echo -e "  📝 Registered $SUBSCRIPTION_COUNT topic→event mappings"
