#!/bin/bash

# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔
# This script is part of Bannou's code generation pipeline.
# DO NOT MODIFY without EXPLICIT user instructions to change code generation.
#
# Changes to generation scripts silently break builds across ALL 48 services.
# An agent once changed namespace strings across 4 scripts in a single commit,
# breaking every service. If you believe a change is needed:
#   1. STOP and explain what you think is wrong
#   2. Show the EXACT diff you propose
#   3. Wait for EXPLICIT approval before touching ANY generation script
#
# This applies to: namespace strings, output paths, exclusion logic,
# NSwag parameters, post-processing steps, and file naming conventions.
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔

# Generate models (DTOs) from OpenAPI schema
# Also generates lifecycle event models from {service}-lifecycle-events.yaml if present
# Usage: ./generate-models.sh <service-name> [schema-file]

set -e  # Exit on any error

# Source common utilities
source "$(dirname "$0")/common.sh"

# Validate arguments
if [ $# -lt 1 ]; then
    log_error "Usage: $0 <service-name> [schema-file]"
    echo "Example: $0 account"
    echo "Example: $0 account ../schemas/account-api.yaml"
    exit 1
fi

SERVICE_NAME="$1"
SCHEMA_FILE="${2:-../schemas/${SERVICE_NAME}-api.yaml}"

SERVICE_PASCAL=$(to_pascal_case "$SERVICE_NAME")
OUTPUT_DIR="../bannou-service/Generated/Models"
OUTPUT_FILE="$OUTPUT_DIR/${SERVICE_PASCAL}Models.cs"

echo -e "${YELLOW}🔧 Generating models for service: $SERVICE_NAME${NC}"
echo -e "  📋 Schema: $SCHEMA_FILE"
echo -e "  📁 Output: $OUTPUT_FILE"

# Validate schema file exists
if [ ! -f "$SCHEMA_FILE" ]; then
    echo -e "${RED}❌ Schema file not found: $SCHEMA_FILE${NC}"
    exit 1
fi

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

# Find NSwag executable and ensure DOTNET_ROOT is set
require_nswag
ensure_dotnet_root

# Run resolver to handle cross-file allOf refs (creates resolved schema if needed)
SCRIPT_DIR="$(dirname "$0")"
echo -e "${YELLOW}🔄 Checking for cross-file allOf refs...${NC}"
python3 "$SCRIPT_DIR/resolve-api-refs.py" "$SERVICE_NAME" 2>&1 | while read line; do echo "  $line"; done

# Check if a resolved version exists (for schemas with cross-file allOf refs)
RESOLVED_SCHEMA="../schemas/Generated/${SERVICE_NAME}-api-resolved.yaml"
if [ -f "$RESOLVED_SCHEMA" ]; then
    echo -e "${BLUE}ℹ️  Using resolved schema (cross-file allOf refs inlined)${NC}"
    SCHEMA_TO_PROCESS="$RESOLVED_SCHEMA"
else
    SCHEMA_TO_PROCESS="$SCHEMA_FILE"
fi

# Base NSwag configuration
EXCLUDED_TYPES="ApiException,ApiException\<TResult\>"
ADDITIONAL_NAMESPACES="BeyondImmersion.BannouService,BeyondImmersion.BannouService.$SERVICE_PASCAL"

# NOTE: Do NOT exclude inlined types from resolved schemas
# The x-inlined-types field tracks types inlined from other service schemas
# (e.g., VoiceTier from voice-api.yaml) - these need to be GENERATED, not excluded.
# Only types from common-api.yaml should be excluded (handled below).

# Extract $refs to common-api.yaml types (shared types like EntityType)
# These are generated once in CommonApiModels.cs, so we exclude them
# Use the ORIGINAL schema file for ref extraction (not resolved)
COMMON_API_REFS=$(extract_common_api_refs "$SCHEMA_FILE")
if [ -n "$COMMON_API_REFS" ]; then
    echo -e "${BLUE}ℹ️  Found common-api.yaml refs - excluding shared types${NC}"
    echo -e "  📦 Common types: $COMMON_API_REFS"
    EXCLUDED_TYPES="$EXCLUDED_TYPES,$COMMON_API_REFS"
    # Common types are in BeyondImmersion.BannouService namespace (generated by generate-common-api.sh)
fi

# Extract SDK type mappings from schema (x-sdk-type extensions)
# This allows schemas to reference types from external SDKs without generating duplicates
SDK_TYPES_OUTPUT=$(python3 "$SCRIPT_DIR/extract-sdk-types.py" "$SCHEMA_FILE" --format=shell 2>/dev/null || echo "")

if [ -n "$SDK_TYPES_OUTPUT" ]; then
    # Parse the shell output (EXCLUDED_TYPES=... and SDK_NAMESPACES=...)
    SDK_EXCLUDED=$(echo "$SDK_TYPES_OUTPUT" | grep "^EXCLUDED_TYPES=" | cut -d'=' -f2)
    SDK_NAMESPACES=$(echo "$SDK_TYPES_OUTPUT" | grep "^SDK_NAMESPACES=" | cut -d'=' -f2)

    if [ -n "$SDK_EXCLUDED" ]; then
        echo -e "${BLUE}ℹ️  Found x-sdk-type annotations - excluding SDK types from generation${NC}"
        echo -e "  📦 SDK types: $SDK_EXCLUDED"
        EXCLUDED_TYPES="$EXCLUDED_TYPES,$SDK_EXCLUDED"
    fi

    if [ -n "$SDK_NAMESPACES" ]; then
        echo -e "  📁 SDK namespaces: $SDK_NAMESPACES"
        ADDITIONAL_NAMESPACES="$ADDITIONAL_NAMESPACES,$SDK_NAMESPACES"
    fi
fi

# Generate models using NSwag (DTOs only)
echo -e "${YELLOW}🔄 Running NSwag model generation...${NC}"

"$NSWAG_EXE" openapi2csclient \
    "/input:$SCHEMA_TO_PROCESS" \
    "/output:$OUTPUT_FILE" \
    "/namespace:BeyondImmersion.BannouService.$SERVICE_PASCAL" \
    "/generateClientClasses:false" \
    "/generateClientInterfaces:false" \
    "/generateDtoTypes:true" \
    "/excludedTypeNames:$EXCLUDED_TYPES" \
    "/jsonLibrary:SystemTextJson" \
    "/generateNullableReferenceTypes:true" \
    "/newLineBehavior:LF" \
    "/templateDirectory:../templates/nswag" \
    "/additionalNamespaceUsages:$ADDITIONAL_NAMESPACES"

# Check if generation succeeded
if [ $? -eq 0 ] && [ -f "$OUTPUT_FILE" ]; then
    # Post-process: Add [JsonRequired] after each [Required] attribute
    # NSwag generates [System.ComponentModel.DataAnnotations.Required] which is ignored by System.Text.Json
    # We add [System.Text.Json.Serialization.JsonRequired] which IS enforced during deserialization
    echo -e "${YELLOW}🔄 Post-processing: Adding [JsonRequired] attributes...${NC}"
    sed -i 's/\(\[System\.ComponentModel\.DataAnnotations\.Required[^]]*\]\)/\1\n    [System.Text.Json.Serialization.JsonRequired]/g' "$OUTPUT_FILE"

    # Post-process: Wrap enums with CS1591 pragma suppressions (enum members cannot have XML docs)
    echo -e "${YELLOW}🔄 Post-processing: Adding enum CS1591 suppressions...${NC}"
    postprocess_enum_suppressions "$OUTPUT_FILE"

    # Post-process: Add XML docs to AdditionalProperties
    echo -e "${YELLOW}🔄 Post-processing: Adding AdditionalProperties XML docs...${NC}"
    postprocess_additional_properties_docs "$OUTPUT_FILE"

    # Post-process: Convert enum member names to proper PascalCase
    echo -e "${YELLOW}🔄 Post-processing: Converting enum names to PascalCase...${NC}"
    postprocess_enum_pascalcase "$OUTPUT_FILE"

    FILE_SIZE=$(wc -l < "$OUTPUT_FILE" 2>/dev/null || echo "0")
    echo -e "${GREEN}✅ Generated models ($FILE_SIZE lines)${NC}"
else
    echo -e "${RED}❌ Failed to generate models${NC}"
    exit 1
fi

# Generate lifecycle event C# models if lifecycle events YAML exists
# The YAML is produced by generate-lifecycle-events.py (from x-lifecycle in *-events.yaml)
# The shared function handles ref resolution, NSwag invocation, and post-processing
if ! generate_lifecycle_event_models "$SERVICE_NAME"; then
    exit 1
fi

exit 0
