#!/usr/bin/env python3
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔
# This script is part of Bannou's code generation pipeline.
# DO NOT MODIFY without EXPLICIT user instructions to change code generation.
#
# Changes to generation scripts silently break builds across ALL 76+ services.
# An agent once changed namespace strings across 4 scripts in a single commit,
# breaking every service. If you believe a change is needed:
#   1. STOP and explain what you think is wrong
#   2. Show the EXACT diff you propose
#   3. Wait for EXPLICIT approval before touching ANY generation script
#
# This applies to: namespace strings, output paths, exclusion logic,
# NSwag parameters, post-processing steps, and file naming conventions.
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔

"""
Generate Telemetry Metric Constants and Documentation from Schema.

This script reads schemas/telemetry-metrics.yaml and generates:
1. bannou-service/Generated/TelemetryMetrics.cs - Typed constants and metadata
2. docs/generated/GENERATED-TELEMETRY-METRICS.md - Documentation

Usage:
    python3 scripts/generate-telemetry-metrics.py
"""

import re
import sys
from pathlib import Path

# Use ruamel.yaml to parse YAML files
try:
    from ruamel.yaml import YAML
    yaml = YAML()
    yaml.preserve_quotes = True
except ImportError:
    print("ERROR: ruamel.yaml is required. Install with: pip install ruamel.yaml")
    sys.exit(1)


def metric_name_to_constant(metric_name: str, override: str | None = None) -> str:
    """Convert a metric name to a C# constant name.

    If override is provided, returns it directly (for cases where automatic
    derivation doesn't match established constant names).

    Otherwise strips the 'bannou.' prefix, splits on '.', PascalCases each
    segment, and joins.
    Examples:
        bannou.state.operations -> StateOperations
        bannou.messaging.published -> MessagingPublished
        bannou.analytics.score.processed -> AnalyticsScoreProcessed
        bannou.messaging.retry_buffer_depth -> MessagingRetryBufferDepth
        bannou.mesh.duration_seconds + override "MeshDuration" -> MeshDuration
    """
    if override:
        return override

    name = metric_name
    if name.startswith('bannou.'):
        name = name[7:]

    # Split on dots, then handle underscores within each segment
    parts = []
    for segment in name.split('.'):
        # Split on underscores and capitalize each part
        sub_parts = segment.split('_')
        parts.extend(sub_parts)

    return ''.join(p.capitalize() for p in parts)


def component_key_to_constant(key: str) -> str:
    """Convert a component key to a C# constant name (PascalCase).

    Examples:
        state -> State
        messaging -> Messaging
        mesh -> Mesh
        analytics -> Analytics
    """
    parts = re.split(r'[-_]', key)
    return ''.join(p.capitalize() for p in parts)


def generate_csharp(components: dict, metrics: dict) -> str:
    """Generate C# code for TelemetryMetrics.cs."""
    lines = [
        "// <auto-generated>",
        "// This file is auto-generated from schemas/telemetry-metrics.yaml",
        "// Do not edit manually - regenerate with: python3 scripts/generate-telemetry-metrics.py",
        "// </auto-generated>",
        "",
        "#nullable enable",
        "",
        "namespace BeyondImmersion.BannouService.Services;",
        "",
    ]

    # ---- TelemetryComponents class ----
    lines.append("/// <summary>")
    lines.append("/// Standard component names for telemetry instrumentation.")
    lines.append("/// Generated from schemas/telemetry-metrics.yaml.")
    lines.append("/// </summary>")
    lines.append("public static class TelemetryComponents")
    lines.append("{")

    for key in sorted(components.keys()):
        comp = components[key]
        const_name = component_key_to_constant(key)
        description = comp.get('description', '')
        lines.append(f"    /// <summary>{description}</summary>")
        lines.append(f'    public const string {const_name} = "{comp["name"]}";')
        lines.append("")

    lines.append("}")
    lines.append("")

    # ---- TelemetryMetrics class ----
    lines.append("/// <summary>")
    lines.append("/// Standard metric names for telemetry instrumentation.")
    lines.append("/// Generated from schemas/telemetry-metrics.yaml.")
    lines.append("/// </summary>")
    lines.append("public static class TelemetryMetrics")
    lines.append("{")
    lines.append("    #region Metric Name Constants")
    lines.append("")

    # Group metrics by component for organization
    metrics_by_component: dict[str, list[tuple[str, dict]]] = {}
    for metric_name, metric_config in metrics.items():
        comp = metric_config.get('component', 'unknown')
        if comp not in metrics_by_component:
            metrics_by_component[comp] = []
        metrics_by_component[comp].append((metric_name, metric_config))

    for comp_key in sorted(metrics_by_component.keys()):
        comp_display = components.get(comp_key, {}).get('description', comp_key)
        lines.append(f"    // {comp_display}")
        for metric_name, metric_config in sorted(metrics_by_component[comp_key], key=lambda x: x[0]):
            override = metric_config.get('constant-name')
            const_name = metric_name_to_constant(metric_name, override)
            description = metric_config.get('description', '')
            metric_type = metric_config.get('type', 'counter')
            tags = metric_config.get('tags', [])

            # Build XML doc
            lines.append(f"    /// <summary>")
            lines.append(f"    /// {description}")
            if tags:
                tag_names = ', '.join(t['name'] for t in tags)
                lines.append(f"    /// Tagged by {tag_names}.")
            lines.append(f"    /// </summary>")
            lines.append(f'    public const string {const_name} = "{metric_name}";')
            lines.append("")

        lines.append("")

    lines.append("    #endregion")
    lines.append("")
    lines.append("    #region Metadata")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// Metric metadata for structural validation and documentation.")
    lines.append("    /// </summary>")
    lines.append("    public static readonly IReadOnlyDictionary<string, MetricMetadata> Metadata =")
    lines.append("        new Dictionary<string, MetricMetadata>")
    lines.append("        {")

    for metric_name, metric_config in sorted(metrics.items()):
        override = metric_config.get('constant-name')
        const_name = metric_name_to_constant(metric_name, override)
        comp_key = metric_config.get('component', 'unknown')
        metric_type = metric_config.get('type', 'counter')
        service = metric_config.get('service', '')
        description = metric_config.get('description', '').replace('"', '\\"')
        lines.append(f'            [{const_name}] = new MetricMetadata("{comp_key}", "{metric_type}", "{service}", "{description}"),')

    lines.append("        };")
    lines.append("")
    lines.append("    #endregion")
    lines.append("}")
    lines.append("")
    lines.append("/// <summary>")
    lines.append("/// Metadata about a telemetry metric for structural validation and documentation.")
    lines.append("/// </summary>")
    lines.append("/// <param name=\"Component\">Component key (e.g., \"state\", \"messaging\", \"analytics\").</param>")
    lines.append("/// <param name=\"Type\">Metric instrument type (counter, histogram, gauge).</param>")
    lines.append("/// <param name=\"Service\">PascalCase service name that emits this metric.</param>")
    lines.append("/// <param name=\"Description\">Human-readable description.</param>")
    lines.append("public readonly record struct MetricMetadata(string Component, string Type, string Service, string Description);")
    lines.append("")

    return '\n'.join(lines)


def generate_markdown(components: dict, metrics: dict) -> str:
    """Generate markdown documentation for GENERATED-TELEMETRY-METRICS.md."""
    lines = [
        "# Generated Telemetry Metrics Reference",
        "",
        "> **Source**: `schemas/telemetry-metrics.yaml`",
        "> **Do not edit manually** - regenerate with `make generate-docs`",
        "",
        "This document lists all telemetry components and metrics used in Bannou.",
        "",
        "## Components",
        "",
        "| Component | Name | Service | Description |",
        "|-----------|------|---------|-------------|",
    ]

    for key in sorted(components.keys()):
        comp = components[key]
        lines.append(f"| `{key}` | `{comp['name']}` | {comp.get('service', '')} | {comp.get('description', '')} |")

    lines.extend([
        "",
        "## Metrics",
        "",
    ])

    # Group by component
    metrics_by_component: dict[str, list[tuple[str, dict]]] = {}
    for metric_name, metric_config in metrics.items():
        comp = metric_config.get('component', 'unknown')
        if comp not in metrics_by_component:
            metrics_by_component[comp] = []
        metrics_by_component[comp].append((metric_name, metric_config))

    for comp_key in sorted(metrics_by_component.keys()):
        comp_display = components.get(comp_key, {}).get('description', comp_key)
        lines.append(f"### {comp_display}")
        lines.append("")
        lines.append("| Metric | Type | Service | Description | Tags |")
        lines.append("|--------|------|---------|-------------|------|")

        for metric_name, metric_config in sorted(metrics_by_component[comp_key], key=lambda x: x[0]):
            metric_type = metric_config.get('type', 'counter')
            service = metric_config.get('service', '')
            description = metric_config.get('description', '')
            tags = metric_config.get('tags', [])
            tag_str = ', '.join(f"`{t['name']}`" for t in tags) if tags else '—'
            lines.append(f"| `{metric_name}` | {metric_type} | {service} | {description} | {tag_str} |")

        lines.append("")

    # Counts
    counter_count = sum(1 for m in metrics.values() if m.get('type') == 'counter')
    histogram_count = sum(1 for m in metrics.values() if m.get('type') == 'histogram')
    gauge_count = sum(1 for m in metrics.values() if m.get('type') == 'gauge')

    lines.extend([
        f"**Total**: {len(metrics)} metrics ({counter_count} counters, {histogram_count} histograms, {gauge_count} gauges) across {len(components)} components",
        "",
        "## Generated Code",
        "",
        "Telemetry metric definitions are generated to `bannou-service/Generated/TelemetryMetrics.cs`,",
        "providing:",
        "",
        "- **Component constants**: `TelemetryComponents.State`, `TelemetryComponents.Analytics`, etc.",
        "- **Metric constants**: `TelemetryMetrics.StateOperations`, `TelemetryMetrics.AnalyticsScoreProcessed`, etc.",
        "- **Metadata**: `TelemetryMetrics.Metadata` dictionary for structural validation",
        "",
        "---",
        "",
        "*This file is auto-generated. See [TENETS.md](../reference/TENETS.md) for architectural context.*",
        "",
    ])

    return '\n'.join(lines)


def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent

    # Read schema
    schema_file = repo_root / 'schemas' / 'telemetry-metrics.yaml'
    if not schema_file.exists():
        print(f"ERROR: Schema file not found: {schema_file}")
        sys.exit(1)

    with open(schema_file) as f:
        content = yaml.load(f)

    if content is None:
        print("ERROR: Failed to parse schema file")
        sys.exit(1)

    components = content.get('x-telemetry-components', {})
    metrics = content.get('x-telemetry-metrics', {})

    if not components:
        print("Warning: No telemetry components defined in schema")
    if not metrics:
        print("Warning: No telemetry metrics defined in schema")

    # Validate component references
    for metric_name, metric_config in metrics.items():
        comp = metric_config.get('component')
        if comp and comp not in components:
            print(f"ERROR: Metric '{metric_name}' references unknown component '{comp}'")
            sys.exit(1)

    # Generate C# code
    csharp_code = generate_csharp(components, metrics)
    csharp_output = repo_root / 'bannou-service' / 'Generated' / 'TelemetryMetrics.cs'
    csharp_output.parent.mkdir(parents=True, exist_ok=True)
    with open(csharp_output, 'w') as f:
        f.write(csharp_code)
    print(f"Generated {csharp_output}")

    # Generate documentation
    markdown = generate_markdown(components, metrics)
    md_output = repo_root / 'docs' / 'generated' / 'GENERATED-TELEMETRY-METRICS.md'
    with open(md_output, 'w') as f:
        f.write(markdown)
    print(f"Generated {md_output}")

    print(f"Processed {len(components)} components and {len(metrics)} metrics")


if __name__ == '__main__':
    main()
