#!/usr/bin/env python3
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔
# This script is part of Bannou's code generation pipeline.
# DO NOT MODIFY without EXPLICIT user instructions to change code generation.
#
# Changes to generation scripts silently break builds across ALL 48 services.
# An agent once changed namespace strings across 4 scripts in a single commit,
# breaking every service. If you believe a change is needed:
#   1. STOP and explain what you think is wrong
#   2. Show the EXACT diff you propose
#   3. Wait for EXPLICIT approval before touching ANY generation script
#
# This applies to: namespace strings, output paths, exclusion logic,
# NSwag parameters, post-processing steps, and file naming conventions.
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔

"""
Generate Variable Provider Code and Documentation from Schema.

This script reads schemas/variable-providers.yaml and generates:
1. bannou-service/Generated/VariableProviderDefinitions.cs - Typed constants and metadata
2. docs/GENERATED-VARIABLE-PROVIDERS.md - Documentation

Usage:
    python3 scripts/generate-variable-providers.py
"""

import re
import sys
from pathlib import Path

# Use ruamel.yaml to parse YAML files
try:
    from ruamel.yaml import YAML
    yaml = YAML()
    yaml.preserve_quotes = True
except ImportError:
    print("ERROR: ruamel.yaml is required. Install with: pip install ruamel.yaml")
    sys.exit(1)


def to_pascal_case(name: str) -> str:
    """Convert kebab-case or snake_case to PascalCase."""
    # Split on hyphens and underscores
    parts = re.split(r'[-_]', name)
    # Capitalize each part
    return ''.join(p.capitalize() for p in parts)


def generate_csharp(providers: dict) -> str:
    """Generate C# code for VariableProviderDefinitions.cs."""
    lines = [
        "// <auto-generated>",
        "// This file is auto-generated from schemas/variable-providers.yaml",
        "// Do not edit manually - regenerate with: python3 scripts/generate-variable-providers.py",
        "//",
        "// Variable provider names are used as ABML expression namespaces.",
        "// For example, the \"personality\" provider enables ${personality.*} expressions.",
        "// All provider factories MUST use these constants for their ProviderName property.",
        "// See: docs/reference/SERVICE-HIERARCHY.md (Variable Provider Factory Pattern)",
        "// </auto-generated>",
        "",
        "#nullable enable",
        "",
        "namespace BeyondImmersion.BannouService.Services;",
        "",
        "/// <summary>",
        "/// Variable provider name constants and metadata definitions.",
        "/// Generated from schemas/variable-providers.yaml.",
        "/// </summary>",
        "public static class VariableProviderDefinitions",
        "{",
        "    #region Provider Name Constants",
        "",
    ]

    # Group providers by service for organization
    providers_by_service: dict[str, list[tuple[str, dict]]] = {}
    for provider_name, provider_config in providers.items():
        service = provider_config.get('service', 'Unknown')
        if service not in providers_by_service:
            providers_by_service[service] = []
        providers_by_service[service].append((provider_name, provider_config))

    # Generate constants grouped by service
    for service in sorted(providers_by_service.keys()):
        service_providers = providers_by_service[service]
        lines.append(f"    // {service} Service")
        for provider_name, provider_config in sorted(service_providers, key=lambda x: x[0]):
            const_name = to_pascal_case(provider_name)
            purpose = provider_config.get('purpose', '')
            lines.append(f"    /// <summary>{purpose}</summary>")
            lines.append(f'    public const string {const_name} = "{provider_name}";')
        lines.append("")

    lines.append("    #endregion")
    lines.append("")
    lines.append("    #region Metadata")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// Provider metadata for documentation, validation, and tooling.")
    lines.append("    /// </summary>")
    lines.append("    public static readonly IReadOnlyDictionary<string, ProviderMetadata> Metadata =")
    lines.append("        new Dictionary<string, ProviderMetadata>")
    lines.append("        {")

    for provider_name, provider_config in sorted(providers.items()):
        service = provider_config.get('service', 'Unknown')
        purpose = provider_config.get('purpose', '').replace('"', '\\"')
        lines.append(f'            [{to_pascal_case(provider_name)}] = new ProviderMetadata("{service}", "{purpose}"),')

    lines.append("        };")
    lines.append("")
    lines.append("    #endregion")
    lines.append("}")
    lines.append("")
    lines.append("/// <summary>")
    lines.append("/// Metadata about a variable provider for documentation and tooling.")
    lines.append("/// </summary>")
    lines.append("/// <param name=\"Service\">Service plugin that owns and registers this provider.</param>")
    lines.append("/// <param name=\"Purpose\">Human-readable description of what data this provider exposes.</param>")
    lines.append("public readonly record struct ProviderMetadata(string Service, string Purpose);")
    lines.append("")

    return '\n'.join(lines)


def generate_markdown(providers: dict) -> str:
    """Generate markdown documentation for GENERATED-VARIABLE-PROVIDERS.md."""
    lines = [
        "# Generated Variable Provider Reference",
        "",
        "> **Source**: `schemas/variable-providers.yaml`",
        "> **Do not edit manually** - regenerate with `make generate-docs`",
        "",
        "This document lists all ABML variable providers used by the Actor runtime.",
        "Variable providers supply entity data to behavior expressions via the",
        "`IVariableProviderFactory` / `IVariableProvider` pattern.",
        "",
        "## Variable Providers",
        "",
        "| Namespace | Service | Purpose |",
        "|-----------|---------|---------|",
    ]

    # Sort providers by name
    for provider_name, provider_config in sorted(providers.items()):
        service = provider_config.get('service', 'Unknown')
        purpose = provider_config.get('purpose', '')
        lines.append(f"| `${{{provider_name}.*}}` | {service} | {purpose} |")

    lines.extend([
        "",
        f"**Total**: {len(providers)} providers",
        "",
        "## How Providers Work",
        "",
        "1. **Schema**: Provider namespaces are defined in `schemas/variable-providers.yaml`",
        "2. **Constants**: Generated to `VariableProviderDefinitions` in `bannou-service/Generated/`",
        "3. **Registration**: Each plugin registers its `IVariableProviderFactory` implementation via DI",
        "4. **Discovery**: Actor runtime discovers all factories via `IEnumerable<IVariableProviderFactory>`",
        "5. **Resolution**: ABML expressions like `${personality.openness}` resolve the `personality` namespace,",
        "   then delegate to the provider for sub-path resolution",
        "",
        "## Usage in ABML",
        "",
        "```yaml",
        "# Access personality traits",
        "condition: ${personality.openness} > 0.7",
        "",
        "# Check quest state",
        "condition: ${quest.active_count} > 0",
        "",
        "# Encounter sentiment",
        "condition: ${encounters.sentiment.{targetId}} < -0.5",
        "```",
        "",
        "## Generated Code",
        "",
        "Variable provider definitions are generated to `bannou-service/Generated/VariableProviderDefinitions.cs`,",
        "providing:",
        "",
        "- **Name constants**: `VariableProviderDefinitions.Personality`, `VariableProviderDefinitions.Quest`, etc.",
        "- **Metadata**: `VariableProviderDefinitions.Metadata` for validation and tooling",
        "",
        "---",
        "",
        "*This file is auto-generated. See [TENETS.md](reference/TENETS.md) for architectural context.*",
        "",
    ])

    return '\n'.join(lines)


def main():
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent

    # Read schema
    schema_file = repo_root / 'schemas' / 'variable-providers.yaml'
    if not schema_file.exists():
        print(f"ERROR: Schema file not found: {schema_file}")
        sys.exit(1)

    with open(schema_file) as f:
        content = yaml.load(f)

    if content is None:
        print("ERROR: Failed to parse schema file")
        sys.exit(1)

    providers = content.get('x-variable-providers', {})
    if not providers:
        print("Warning: No variable providers defined in schema")

    # Generate C# code
    csharp_code = generate_csharp(providers)
    csharp_output = repo_root / 'bannou-service' / 'Generated' / 'VariableProviderDefinitions.cs'
    csharp_output.parent.mkdir(parents=True, exist_ok=True)
    with open(csharp_output, 'w') as f:
        f.write(csharp_code)
    print(f"Generated {csharp_output}")

    # Generate documentation
    markdown = generate_markdown(providers)
    md_output = repo_root / 'docs' / 'GENERATED-VARIABLE-PROVIDERS.md'
    with open(md_output, 'w') as f:
        f.write(markdown)
    print(f"Generated {md_output}")

    print(f"Processed {len(providers)} variable providers")


if __name__ == '__main__':
    main()
