#!/bin/bash

# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔
# This script is part of Bannou's code generation pipeline.
# DO NOT MODIFY without EXPLICIT user instructions to change code generation.
#
# Changes to generation scripts silently break builds across ALL 48 services.
# An agent once changed namespace strings across 4 scripts in a single commit,
# breaking every service. If you believe a change is needed:
#   1. STOP and explain what you think is wrong
#   2. Show the EXACT diff you propose
#   3. Wait for EXPLICIT approval before touching ANY generation script
#
# This applies to: namespace strings, output paths, exclusion logic,
# NSwag parameters, post-processing steps, and file naming conventions.
# ⛔⛔⛔ AGENT MODIFICATION PROHIBITED ⛔⛔⛔

# Generate service-specific event models from {service}-events.yaml files
# These models are placed in bannou-service/Generated/Events/ so all services can reference them
# Excludes: *-lifecycle-events.yaml, *-client-events.yaml, common-events.yaml

set -e

# Change to scripts directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Source common utilities
source "./common.sh"

log_info "📡 Generating service-specific event models"

# Find NSwag executable and ensure DOTNET_ROOT is set
require_nswag
ensure_dotnet_root

# Pre-process: Resolve complex cross-file refs that NSwag can't handle
# This creates resolved versions in schemas/Generated/ for schemas with complex refs
log_info "Pre-processing: Resolving complex cross-file refs..."
if python3 "$SCRIPT_DIR/resolve-event-refs.py"; then
    log_success "Complex refs resolved successfully"
else
    log_error "Failed to resolve complex refs"
    exit 1
fi
echo ""

# Target directory for generated models
TARGET_DIR="../bannou-service/Generated/Events"
mkdir -p "$TARGET_DIR"

# Track generated files
GENERATED_COUNT=0
FAILED_COUNT=0

# Process each service-specific events yaml file
for EVENTS_SCHEMA in ../schemas/*-events.yaml; do
    # Skip lifecycle events (auto-generated from x-lifecycle)
    if [[ "$EVENTS_SCHEMA" == *"-lifecycle-events.yaml" ]]; then
        continue
    fi

    # Skip client events (server-to-client WebSocket push)
    if [[ "$EVENTS_SCHEMA" == *"-client-events.yaml" ]]; then
        continue
    fi

    # Skip common events (processed by generate-common-events.sh)
    if [[ "$EVENTS_SCHEMA" == *"common-events.yaml" ]]; then
        continue
    fi

    # Extract service name from filename
    FILENAME=$(basename "$EVENTS_SCHEMA")
    SERVICE_NAME="${FILENAME%-events.yaml}"
    SERVICE_PASCAL=$(to_pascal_case "$SERVICE_NAME")

    OUTPUT_FILE="${TARGET_DIR}/${SERVICE_PASCAL}EventsModels.cs"

    # Check if a resolved version exists (for schemas with complex cross-file refs)
    RESOLVED_SCHEMA="../schemas/Generated/${SERVICE_NAME}-events-resolved.yaml"
    if [ -f "$RESOLVED_SCHEMA" ]; then
        SCHEMA_TO_PROCESS="$RESOLVED_SCHEMA"
        echo -e "${YELLOW}Generating ${SERVICE_PASCAL} events from ${FILENAME} (using resolved version)...${NC}"
    else
        SCHEMA_TO_PROCESS="$EVENTS_SCHEMA"
        echo -e "${YELLOW}Generating ${SERVICE_PASCAL} events from ${FILENAME}...${NC}"
    fi

    # Extract $refs to common-api.yaml types (shared types like EntityType)
    # These are always excluded since they're generated by generate-common-api.sh
    COMMON_REFS=$(extract_common_api_refs "$EVENTS_SCHEMA")

    # Extract API refs from ORIGINAL schema (even if using resolved version)
    # These types exist in the service's API namespace and should be excluded
    API_REFS=$(extract_api_refs "$EVENTS_SCHEMA" "$SERVICE_NAME" "$SERVICE_PASCAL")

    # Build exclusion list and namespace usages
    EXCLUSIONS="ApiException,ApiException\<TResult\>,BaseServiceEvent"
    NAMESPACE_USAGES="BeyondImmersion.Bannou.Core,BeyondImmersion.BannouService"

    if [ "$SCHEMA_TO_PROCESS" = "$RESOLVED_SCHEMA" ]; then
        echo -e "  ${BLUE}Using resolved schema (complex refs inlined for NSwag)${NC}"
        # Extract ALL inlined types from resolved schema - these are API types that need exclusion
        INLINED_TYPES=$(extract_inlined_types "$RESOLVED_SCHEMA")
        if [ -n "$INLINED_TYPES" ]; then
            EXCLUSIONS="${EXCLUSIONS},${INLINED_TYPES}"
            echo -e "  ${BLUE}Excluding inlined API types: ${INLINED_TYPES}${NC}"
        fi
    fi

    # Always exclude API refs (simple types like enums that aren't inlined but are referenced)
    if [ -n "$API_REFS" ]; then
        EXCLUSIONS="${EXCLUSIONS},${API_REFS}"
        NAMESPACE_USAGES="${NAMESPACE_USAGES},BeyondImmersion.BannouService.${SERVICE_PASCAL}"
        echo -e "  ${BLUE}Excluding API types: ${API_REFS}${NC}"
    fi

    if [ -n "$COMMON_REFS" ]; then
        EXCLUSIONS="${EXCLUSIONS},${COMMON_REFS}"
        # Common types are in BeyondImmersion.BannouService namespace (generated by generate-common-api.sh)
        echo -e "  ${BLUE}Excluding common types: ${COMMON_REFS}${NC}"
    fi

    # Generate models using NSwag (use resolved schema if available)
    "$NSWAG_EXE" openapi2csclient \
        "/input:$SCHEMA_TO_PROCESS" \
        "/output:$OUTPUT_FILE" \
        "/namespace:BeyondImmersion.BannouService.Events" \
        "/generateClientClasses:false" \
        "/generateClientInterfaces:false" \
        "/generateDtoTypes:true" \
        "/excludedTypeNames:${EXCLUSIONS}" \
        "/additionalNamespaceUsages:${NAMESPACE_USAGES}" \
        "/jsonLibrary:SystemTextJson" \
        "/generateNullableReferenceTypes:true" \
        "/newLineBehavior:LF" \
        "/templateDirectory:../templates/nswag" 2>&1

    if [ $? -eq 0 ]; then
        # Post-process: Add [JsonRequired] after each [Required] attribute
        sed -i 's/\(\[System\.ComponentModel\.DataAnnotations\.Required[^]]*\]\)/\1\n    [System.Text.Json.Serialization.JsonRequired]/g' "$OUTPUT_FILE"
        # Post-process: Fix EventName shadowing - add 'override' keyword
        sed -i 's/public string EventName { get; set; }/public override string EventName { get; set; }/g' "$OUTPUT_FILE"
        # Post-process: Wrap enums with CS1591 pragma suppressions (enum members cannot have XML docs)
        postprocess_enum_suppressions "$OUTPUT_FILE"
        # Post-process: Add XML docs to AdditionalProperties
        postprocess_additional_properties_docs "$OUTPUT_FILE"
        echo -e "${GREEN}  Generated: $OUTPUT_FILE${NC}"
        GENERATED_COUNT=$((GENERATED_COUNT + 1))
    else
        echo -e "${RED}  Failed to generate: $OUTPUT_FILE${NC}"
        FAILED_COUNT=$((FAILED_COUNT + 1))
    fi
done

echo ""
echo -e "${BLUE}========================================${NC}"
if [ $FAILED_COUNT -eq 0 ]; then
    echo -e "${GREEN}Service events generation complete!${NC}"
    echo -e "  Generated: ${GENERATED_COUNT} files"
else
    echo -e "${YELLOW}Service events generation completed with errors${NC}"
    echo -e "  Generated: ${GENERATED_COUNT} files"
    echo -e "  ${RED}Failed: ${FAILED_COUNT} files${NC}"
fi
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}All services can now use: using BeyondImmersion.BannouService.Events;${NC}"
