//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class AccountsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "http://localhost/api/accounts";
    }

    /**
     * Create new user account
     * @return Account created successfully
     */
    createAccount(body: CreateAccountRequest): Promise<CreateAccountResponse> {
        let url_ = this.baseUrl + "/create";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateAccount(_response);
        });
    }

    protected processCreateAccount(response: Response): Promise<CreateAccountResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CreateAccountResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ErrorResponse.fromJS(resultData400);
            return throwException("Invalid request data", status, _responseText, _headers, result400);
            });
        } else if (status === 409) {
            return response.text().then((_responseText) => {
            let result409: any = null;
            let resultData409 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result409 = ErrorResponse.fromJS(resultData409);
            return throwException("Account already exists", status, _responseText, _headers, result409);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ErrorResponse.fromJS(resultData500);
            return throwException("Internal server error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CreateAccountResponse>(null as any);
    }

    /**
     * Retrieve user account
     * @return Account retrieved successfully
     */
    getAccount(body: GetAccountRequest): Promise<GetAccountResponse> {
        let url_ = this.baseUrl + "/get";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAccount(_response);
        });
    }

    protected processGetAccount(response: Response): Promise<GetAccountResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = GetAccountResponse.fromJS(resultData200);
            return result200;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = ErrorResponse.fromJS(resultData400);
            return throwException("Invalid request data", status, _responseText, _headers, result400);
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            let result404: any = null;
            let resultData404 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result404 = ErrorResponse.fromJS(resultData404);
            return throwException("Account not found", status, _responseText, _headers, result404);
            });
        } else if (status === 500) {
            return response.text().then((_responseText) => {
            let result500: any = null;
            let resultData500 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result500 = ErrorResponse.fromJS(resultData500);
            return throwException("Internal server error", status, _responseText, _headers, result500);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<GetAccountResponse>(null as any);
    }
}

/** Request to create a new user account */
export class CreateAccountRequest implements ICreateAccountRequest {
    /** Username - optional if using OAuth */
    username?: string;
    /** Password - optional if using OAuth */
    password?: string;
    /** Steam user ID, if using Steam OAuth */
    steam_id?: string;
    /** Steam user token, if using Steam OAuth */
    steam_token?: string;
    /** Google user ID, if using Google OAuth */
    google_id?: string;
    /** Google user token, if using Google OAuth */
    google_token?: string;
    /** Email address - optional */
    email?: string;
    /** Account creation region - used for routing and metrics */
    region?: string;
    /** Whether the email should be considered verified */
    email_verified?: boolean;
    /** Whether 2-factor authentication has been enabled */
    two_factor_enabled?: boolean;
    /** System-wide role claims (Administrator, User, etc.) */
    role_claims?: string[];
    /** Application access claims, may include licenses */
    app_claims?: string[];
    /** Specific permissions within applications */
    scope_claims?: string[];
    /** Identity-related claims (OAuth tokens, hashed passwords) */
    identity_claims?: string[];
    /** Generic profile information */
    profile_claims?: string[];

    [key: string]: any;

    constructor(data?: ICreateAccountRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.email_verified = false;
            this.two_factor_enabled = false;
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.username = _data["username"];
            this.password = _data["password"];
            this.steam_id = _data["steam_id"];
            this.steam_token = _data["steam_token"];
            this.google_id = _data["google_id"];
            this.google_token = _data["google_token"];
            this.email = _data["email"];
            this.region = _data["region"];
            this.email_verified = _data["email_verified"] !== undefined ? _data["email_verified"] : false;
            this.two_factor_enabled = _data["two_factor_enabled"] !== undefined ? _data["two_factor_enabled"] : false;
            if (Array.isArray(_data["role_claims"])) {
                this.role_claims = [] as any;
                for (let item of _data["role_claims"])
                    this.role_claims!.push(item);
            }
            if (Array.isArray(_data["app_claims"])) {
                this.app_claims = [] as any;
                for (let item of _data["app_claims"])
                    this.app_claims!.push(item);
            }
            if (Array.isArray(_data["scope_claims"])) {
                this.scope_claims = [] as any;
                for (let item of _data["scope_claims"])
                    this.scope_claims!.push(item);
            }
            if (Array.isArray(_data["identity_claims"])) {
                this.identity_claims = [] as any;
                for (let item of _data["identity_claims"])
                    this.identity_claims!.push(item);
            }
            if (Array.isArray(_data["profile_claims"])) {
                this.profile_claims = [] as any;
                for (let item of _data["profile_claims"])
                    this.profile_claims!.push(item);
            }
        }
    }

    static fromJS(data: any): CreateAccountRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateAccountRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["username"] = this.username;
        data["password"] = this.password;
        data["steam_id"] = this.steam_id;
        data["steam_token"] = this.steam_token;
        data["google_id"] = this.google_id;
        data["google_token"] = this.google_token;
        data["email"] = this.email;
        data["region"] = this.region;
        data["email_verified"] = this.email_verified;
        data["two_factor_enabled"] = this.two_factor_enabled;
        if (Array.isArray(this.role_claims)) {
            data["role_claims"] = [];
            for (let item of this.role_claims)
                data["role_claims"].push(item);
        }
        if (Array.isArray(this.app_claims)) {
            data["app_claims"] = [];
            for (let item of this.app_claims)
                data["app_claims"].push(item);
        }
        if (Array.isArray(this.scope_claims)) {
            data["scope_claims"] = [];
            for (let item of this.scope_claims)
                data["scope_claims"].push(item);
        }
        if (Array.isArray(this.identity_claims)) {
            data["identity_claims"] = [];
            for (let item of this.identity_claims)
                data["identity_claims"].push(item);
        }
        if (Array.isArray(this.profile_claims)) {
            data["profile_claims"] = [];
            for (let item of this.profile_claims)
                data["profile_claims"].push(item);
        }
        return data;
    }
}

/** Request to create a new user account */
export interface ICreateAccountRequest {
    /** Username - optional if using OAuth */
    username?: string;
    /** Password - optional if using OAuth */
    password?: string;
    /** Steam user ID, if using Steam OAuth */
    steam_id?: string;
    /** Steam user token, if using Steam OAuth */
    steam_token?: string;
    /** Google user ID, if using Google OAuth */
    google_id?: string;
    /** Google user token, if using Google OAuth */
    google_token?: string;
    /** Email address - optional */
    email?: string;
    /** Account creation region - used for routing and metrics */
    region?: string;
    /** Whether the email should be considered verified */
    email_verified?: boolean;
    /** Whether 2-factor authentication has been enabled */
    two_factor_enabled?: boolean;
    /** System-wide role claims (Administrator, User, etc.) */
    role_claims?: string[];
    /** Application access claims, may include licenses */
    app_claims?: string[];
    /** Specific permissions within applications */
    scope_claims?: string[];
    /** Identity-related claims (OAuth tokens, hashed passwords) */
    identity_claims?: string[];
    /** Generic profile information */
    profile_claims?: string[];

    [key: string]: any;
}

/** Response from account creation */
export class CreateAccountResponse implements ICreateAccountResponse {
    /** Unique account identifier */
    id!: number;
    /** Account username */
    username?: string;
    /** Account email address */
    email?: string;
    /** Email verification status */
    email_verified?: boolean;
    /** Account region */
    region?: string;
    /** Security token for account operations */
    security_token?: string;
    /** 2FA status */
    two_factor_enabled?: boolean;
    /** Account lockout end time (if locked) */
    lockout_end?: Date | undefined;
    /** Last login timestamp */
    last_login_at?: Date | undefined;
    /** Account creation timestamp */
    created_at!: Date;
    /** Last account update timestamp */
    updated_at?: Date | undefined;
    /** Account deletion timestamp (soft delete) */
    deleted_at?: Date | undefined;
    /** Application claims assigned to account */
    app_claims?: string[];
    /** Identity claims assigned to account */
    identity_claims?: string[];

    [key: string]: any;

    constructor(data?: ICreateAccountResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.username = _data["username"];
            this.email = _data["email"];
            this.email_verified = _data["email_verified"];
            this.region = _data["region"];
            this.security_token = _data["security_token"];
            this.two_factor_enabled = _data["two_factor_enabled"];
            this.lockout_end = _data["lockout_end"] ? new Date(_data["lockout_end"].toString()) : undefined as any;
            this.last_login_at = _data["last_login_at"] ? new Date(_data["last_login_at"].toString()) : undefined as any;
            this.created_at = _data["created_at"] ? new Date(_data["created_at"].toString()) : undefined as any;
            this.updated_at = _data["updated_at"] ? new Date(_data["updated_at"].toString()) : undefined as any;
            this.deleted_at = _data["deleted_at"] ? new Date(_data["deleted_at"].toString()) : undefined as any;
            if (Array.isArray(_data["app_claims"])) {
                this.app_claims = [] as any;
                for (let item of _data["app_claims"])
                    this.app_claims!.push(item);
            }
            if (Array.isArray(_data["identity_claims"])) {
                this.identity_claims = [] as any;
                for (let item of _data["identity_claims"])
                    this.identity_claims!.push(item);
            }
        }
    }

    static fromJS(data: any): CreateAccountResponse {
        data = typeof data === 'object' ? data : {};
        let result = new CreateAccountResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["username"] = this.username;
        data["email"] = this.email;
        data["email_verified"] = this.email_verified;
        data["region"] = this.region;
        data["security_token"] = this.security_token;
        data["two_factor_enabled"] = this.two_factor_enabled;
        data["lockout_end"] = this.lockout_end ? this.lockout_end.toISOString() : undefined as any;
        data["last_login_at"] = this.last_login_at ? this.last_login_at.toISOString() : undefined as any;
        data["created_at"] = this.created_at ? this.created_at.toISOString() : undefined as any;
        data["updated_at"] = this.updated_at ? this.updated_at.toISOString() : undefined as any;
        data["deleted_at"] = this.deleted_at ? this.deleted_at.toISOString() : undefined as any;
        if (Array.isArray(this.app_claims)) {
            data["app_claims"] = [];
            for (let item of this.app_claims)
                data["app_claims"].push(item);
        }
        if (Array.isArray(this.identity_claims)) {
            data["identity_claims"] = [];
            for (let item of this.identity_claims)
                data["identity_claims"].push(item);
        }
        return data;
    }
}

/** Response from account creation */
export interface ICreateAccountResponse {
    /** Unique account identifier */
    id: number;
    /** Account username */
    username?: string;
    /** Account email address */
    email?: string;
    /** Email verification status */
    email_verified?: boolean;
    /** Account region */
    region?: string;
    /** Security token for account operations */
    security_token?: string;
    /** 2FA status */
    two_factor_enabled?: boolean;
    /** Account lockout end time (if locked) */
    lockout_end?: Date | undefined;
    /** Last login timestamp */
    last_login_at?: Date | undefined;
    /** Account creation timestamp */
    created_at: Date;
    /** Last account update timestamp */
    updated_at?: Date | undefined;
    /** Account deletion timestamp (soft delete) */
    deleted_at?: Date | undefined;
    /** Application claims assigned to account */
    app_claims?: string[];
    /** Identity claims assigned to account */
    identity_claims?: string[];

    [key: string]: any;
}

/** Request to retrieve account information */
export class GetAccountRequest implements IGetAccountRequest {
    /** Account ID */
    id?: number;
    /** Account username */
    username?: string;
    /** Account email */
    email?: string;
    /** Steam user ID */
    steam_id?: string;
    /** Google user ID */
    google_id?: string;
    /** Specific identity claim to search by */
    identity_claim?: string;
    /** Whether to include all claims in response */
    include_claims?: boolean;

    [key: string]: any;

    constructor(data?: IGetAccountRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.include_claims = false;
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.id = _data["id"];
            this.username = _data["username"];
            this.email = _data["email"];
            this.steam_id = _data["steam_id"];
            this.google_id = _data["google_id"];
            this.identity_claim = _data["identity_claim"];
            this.include_claims = _data["include_claims"] !== undefined ? _data["include_claims"] : false;
        }
    }

    static fromJS(data: any): GetAccountRequest {
        data = typeof data === 'object' ? data : {};
        let result = new GetAccountRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["id"] = this.id;
        data["username"] = this.username;
        data["email"] = this.email;
        data["steam_id"] = this.steam_id;
        data["google_id"] = this.google_id;
        data["identity_claim"] = this.identity_claim;
        data["include_claims"] = this.include_claims;
        return data;
    }
}

/** Request to retrieve account information */
export interface IGetAccountRequest {
    /** Account ID */
    id?: number;
    /** Account username */
    username?: string;
    /** Account email */
    email?: string;
    /** Steam user ID */
    steam_id?: string;
    /** Google user ID */
    google_id?: string;
    /** Specific identity claim to search by */
    identity_claim?: string;
    /** Whether to include all claims in response */
    include_claims?: boolean;

    [key: string]: any;
}

/** Account information response */
export class GetAccountResponse extends CreateAccountResponse implements IGetAccountResponse {
    /** Role claims (only if include_claims=true) */
    role_claims?: string[];
    /** Scope claims (only if include_claims=true) */
    scope_claims?: string[];
    /** Profile claims (only if include_claims=true) */
    profile_claims?: string[];

    [key: string]: any;

    constructor(data?: IGetAccountResponse) {
        super(data);
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            if (Array.isArray(_data["role_claims"])) {
                this.role_claims = [] as any;
                for (let item of _data["role_claims"])
                    this.role_claims!.push(item);
            }
            if (Array.isArray(_data["scope_claims"])) {
                this.scope_claims = [] as any;
                for (let item of _data["scope_claims"])
                    this.scope_claims!.push(item);
            }
            if (Array.isArray(_data["profile_claims"])) {
                this.profile_claims = [] as any;
                for (let item of _data["profile_claims"])
                    this.profile_claims!.push(item);
            }
        }
    }

    static fromJS(data: any): GetAccountResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GetAccountResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        if (Array.isArray(this.role_claims)) {
            data["role_claims"] = [];
            for (let item of this.role_claims)
                data["role_claims"].push(item);
        }
        if (Array.isArray(this.scope_claims)) {
            data["scope_claims"] = [];
            for (let item of this.scope_claims)
                data["scope_claims"].push(item);
        }
        if (Array.isArray(this.profile_claims)) {
            data["profile_claims"] = [];
            for (let item of this.profile_claims)
                data["profile_claims"].push(item);
        }
        super.toJSON(data);
        return data;
    }
}

/** Account information response */
export interface IGetAccountResponse extends ICreateAccountResponse {
    /** Role claims (only if include_claims=true) */
    role_claims?: string[];
    /** Scope claims (only if include_claims=true) */
    scope_claims?: string[];
    /** Profile claims (only if include_claims=true) */
    profile_claims?: string[];

    [key: string]: any;
}

/** Error response */
export class ErrorResponse implements IErrorResponse {
    /** Error type */
    error!: string;
    /** Human-readable error message */
    message!: string;
    /** Additional error details */
    details?: any;

    [key: string]: any;

    constructor(data?: IErrorResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.error = _data["error"];
            this.message = _data["message"];
            this.details = _data["details"];
        }
    }

    static fromJS(data: any): ErrorResponse {
        data = typeof data === 'object' ? data : {};
        let result = new ErrorResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["error"] = this.error;
        data["message"] = this.message;
        data["details"] = this.details;
        return data;
    }
}

/** Error response */
export interface IErrorResponse {
    /** Error type */
    error: string;
    /** Human-readable error message */
    message: string;
    /** Additional error details */
    details?: any;

    [key: string]: any;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}